class Service {
    constructor(name, description, fullText, path){
        this.name = name;
        this.description = description;
        this.fullText = fullText;
        this.path = path;
    }
}

export const services_es = [
    new Service(
        'Servicio 1',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/servicios#1'
    ),
    new Service(
        'Servicio 2',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/servicios#2'
    ),
    new Service(
        'Servicio 3',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/servicios#3'
    ),
    new Service(
        'Servicio 4',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/servicios#4'
    ),
    new Service(
        'Servicio 5',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/servicios#5'
    ),
    new Service(
        'Servicio 6',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/servicios#6'
    ),
];

export const services_en = [
    new Service(
        'Service 1',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/services#1'
    ),
    new Service(
        'Service 2',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/services#2'
    ),
    new Service(
        'Service 3',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/services#3'
    ),
    new Service(
        'Service 4',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/services#4'
    ),
    new Service(
        'Service 5',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/services#5'
    ),
    new Service(
        'Service 6',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum nibh ut risus luctus pellentesque. Maecenas luctus eu eros at molestie. Etiam pharetra nisi hendrerit dapibus faucibus. Integer faucibus magna risus. Fusce a dolor ac nulla efficitur gravida ut et felis. Nam consectetur eget ligula eu commodo. Nunc blandit a elit id viverra. Nunc eget urna quam.Nunc tempus pulvinar massa a aliquet. Praesent faucibus lectus eu sapien scelerisque tempor. Sed aliquam, neque vitae ultricies aliquet, massa turpis pharetra eros, a bibendum turpis neque sit amet sem. Sed convallis semper lacus, et varius nulla pretium sit amet. Integer vel magna ligula. Pellentesque tincidunt dapibus ligula quis eleifend. In efficitur venenatis orci, non venenatis orci iaculis in. Curabitur ultrices quis neque id scelerisque. Nam in pharetra elit.',
        '/services#6'
    ),
];